### ISSUE TITLE
Internationalize all the (controller) things

### ISSUE THREAD

**Issue by pattichan** [pattichan/project-management#16]
A lot of our older controller code uses hard-coded copy.

```ruby
class OrdersController
  def create
    flash[:notice] = "You placed your order, yay!"
  end
end
```

This is less reusable and harder to look at with a lot of copy.

Let's change these to:

```yml
# en.yml
users:
  create:
    success: "You placed your order, yay!"
```

:)
